### ISSUE TITLE
Return code -1

### ISSUE THREAD

**Issue by tprochazka** [candrews/HttpResponseCache#8]
I found very interesting thing. I started using this cache more intensively. I have about 135 files in the cache with total size 1MB.

Sometimes happen that HttpURLConnection start return -1 as HTTP return code instead of 200 and input stream is empty. When I check cache files it contain desired file, it is image and I can display it. Internet connection is OK, but it doesn't try to load new data from server, it still return only -1. If I delete cache it work normally some times. 

I don't understand journal file yet, but it contain 54x hash of file that can't be loaded.

I'm testing it on the Xoom with 4.0.4 Android.

**Comment by candrews** [comment]
Since you're using ICS, can you see if you can reproduce this bug without using this library?Just comment out the line that says: com.integralblue.httpresponsecache.HttpResponseCache.install(httpCacheDir, httpCacheSize)

**Comment by tprochazka** [comment]
I think that I must replace 
`com.integralblue.httpresponsecache.HttpResponseCache.install(httpCacheDir, httpCacheSize)`
by
`android.net.http.HttpResponseCache.install(httpCacheDir, httpCacheSize);`
Not only comment out first one.
I will try it.

**Comment by tprochazka** [comment]
I think that this problem exist also on official implementation and I think that it happen when I use debugging more intensive and often kill and start the application. Maybe file cache implementation is not safe if application is killed.

**Comment by dallasgutauckis** [comment]
I'm also seeing this issue. I'm going to look into a patch. This issue exists both in the officially released version and your compatibility version. See http://code.google.com/p/android/issues/detail?id=7787

**Comment by iNoles** [comment]
I haven't seen this problem. All I did was close InputStream and disconnect URLConnection.

**Comment by dallasgutauckis** [comment]
`ResponseHeaders#combine` is where the status line is lost because result does not have a status line set.

```
result.setStatusLine(headers.getStatusLine());
```

Fixes the issue just after the creation of the new RawHeaders object. Is that the right implementation, @candrews?

**Comment by dallasgutauckis** [comment]
I'm thinking the status line should probably be of the network's status line (304 Not Modified) instead of the cached (200 OK)

```
result.setStatusLine(network.headers.getStatusLine());
```

**Comment by dallasgutauckis** [comment]
See pull request (#10)

**Comment by candrews** [comment]
The fix makes sense to me. It seems to me that since this bug also affects ICS's HttpResponseCache implementation, that the same fix should be made there - could you create an issue in the Android bug tracker, and submit this fix to them?

I also asked the original author of this code in the Android project for his thoughts on the fix.

Thanks for you help - I look forward to having this fixed in this compatibility project and in Android itself soon!

**Comment by candrews** [comment]
Nevermind - Android already has this fix! See 5d7e0fc1af3141aa41e9c21d74da3c36b933517f in Android libcore

Thanks Jesse!

I'm currently copying all the changes from when I last updated this library, which was android-4.0.1_r1, to now (which is currently android-4.1.1_r3). This fix will be included.

**Comment by swankjesse** [comment]
I think upstream already has a fix:
http://omapzoom.org/?p=platform/libcore.git;a=blob;f=luni/src/main/java/libcore/net/http/ResponseHeaders.java;h=003b4457b95036c3b52136df493366fb527db568;hb=HEAD

_update_ ... and now I read that you've seen that too. Sweet.

**Comment by dallasgutauckis** [comment]
Thanks for looking into it and getting back to me. I saw an issue in the bug tracker that I thought was it but it looked like it was targeted for a much earlier version. I guess it was targeted, but not fixed until recently.

**Comment by candrews** [comment]
I finished merging in the Android changes up to version android-4.1.1_r3, and this fix is included. Please test and let me know if this issue occurs again. Thank you!

**Comment by tprochazka** [comment]
Is this failed test related to this issue?
Failed tests:   testConditionalHitUpdatesCache(com.integralblue.httpresponsecache.compat.libcore.net.http.HttpResponseCacheTest): null expected:<[A]> but was:<[B]>
